import type { PodMarketplace } from "@/lib/pricing/types";

export interface MarketplacePricingProfile {
  marketplace: PodMarketplace;
  displayName: string;
  commissionRate: number;
  paymentFeeRate: number;
  paymentFixedFee: number;
  priceEnding: number;
  rankingSensitivity: number;
  reviewSensitivity: number;
  shippingSensitivity: number;
  raceToBottomRisk: number;
  defaultMinMarginPercent: number;
}

export const MARKETPLACE_PRICING_PROFILES: Record<PodMarketplace, MarketplacePricingProfile> = {
  amazon_merch: {
    marketplace: "amazon_merch",
    displayName: "Amazon Merch",
    commissionRate: 0.15,
    paymentFeeRate: 0,
    paymentFixedFee: 0,
    priceEnding: 0.99,
    rankingSensitivity: 0.95,
    reviewSensitivity: 0.85,
    shippingSensitivity: 0.25,
    raceToBottomRisk: 0.72,
    defaultMinMarginPercent: 28,
  },
  etsy: {
    marketplace: "etsy",
    displayName: "Etsy",
    commissionRate: 0.065,
    paymentFeeRate: 0.03,
    paymentFixedFee: 0.25,
    priceEnding: 0.95,
    rankingSensitivity: 0.78,
    reviewSensitivity: 0.92,
    shippingSensitivity: 0.9,
    raceToBottomRisk: 0.8,
    defaultMinMarginPercent: 32,
  },
  printify: {
    marketplace: "printify",
    displayName: "Printify",
    commissionRate: 0,
    paymentFeeRate: 0.029,
    paymentFixedFee: 0.3,
    priceEnding: 0.99,
    rankingSensitivity: 0.35,
    reviewSensitivity: 0.4,
    shippingSensitivity: 0.8,
    raceToBottomRisk: 0.45,
    defaultMinMarginPercent: 35,
  },
  printful: {
    marketplace: "printful",
    displayName: "Printful",
    commissionRate: 0,
    paymentFeeRate: 0.029,
    paymentFixedFee: 0.3,
    priceEnding: 0.99,
    rankingSensitivity: 0.35,
    reviewSensitivity: 0.4,
    shippingSensitivity: 0.75,
    raceToBottomRisk: 0.42,
    defaultMinMarginPercent: 35,
  },
  teepublic: {
    marketplace: "teepublic",
    displayName: "TeePublic",
    commissionRate: 0.22,
    paymentFeeRate: 0,
    paymentFixedFee: 0,
    priceEnding: 0.0,
    rankingSensitivity: 0.72,
    reviewSensitivity: 0.55,
    shippingSensitivity: 0.45,
    raceToBottomRisk: 0.88,
    defaultMinMarginPercent: 24,
  },
  redbubble: {
    marketplace: "redbubble",
    displayName: "Redbubble",
    commissionRate: 0.2,
    paymentFeeRate: 0,
    paymentFixedFee: 0,
    priceEnding: 0.99,
    rankingSensitivity: 0.68,
    reviewSensitivity: 0.5,
    shippingSensitivity: 0.5,
    raceToBottomRisk: 0.82,
    defaultMinMarginPercent: 26,
  },
  shopify: {
    marketplace: "shopify",
    displayName: "Shopify",
    commissionRate: 0,
    paymentFeeRate: 0.029,
    paymentFixedFee: 0.3,
    priceEnding: 0.99,
    rankingSensitivity: 0.3,
    reviewSensitivity: 0.75,
    shippingSensitivity: 0.95,
    raceToBottomRisk: 0.38,
    defaultMinMarginPercent: 40,
  },
  ebay: {
    marketplace: "ebay",
    displayName: "eBay",
    commissionRate: 0.1325,
    paymentFeeRate: 0.029,
    paymentFixedFee: 0.3,
    priceEnding: 0.99,
    rankingSensitivity: 0.78,
    reviewSensitivity: 0.8,
    shippingSensitivity: 0.85,
    raceToBottomRisk: 0.86,
    defaultMinMarginPercent: 30,
  },
  spreadshirt: {
    marketplace: "spreadshirt",
    displayName: "Spreadshirt",
    commissionRate: 0.2,
    paymentFeeRate: 0,
    paymentFixedFee: 0,
    priceEnding: 0.99,
    rankingSensitivity: 0.58,
    reviewSensitivity: 0.45,
    shippingSensitivity: 0.55,
    raceToBottomRisk: 0.68,
    defaultMinMarginPercent: 28,
  },
  spring: {
    marketplace: "spring",
    displayName: "Spring/Teespring",
    commissionRate: 0.12,
    paymentFeeRate: 0,
    paymentFixedFee: 0,
    priceEnding: 0.99,
    rankingSensitivity: 0.54,
    reviewSensitivity: 0.5,
    shippingSensitivity: 0.62,
    raceToBottomRisk: 0.55,
    defaultMinMarginPercent: 34,
  },
  zazzle: {
    marketplace: "zazzle",
    displayName: "Zazzle",
    commissionRate: 0.15,
    paymentFeeRate: 0,
    paymentFixedFee: 0,
    priceEnding: 0.95,
    rankingSensitivity: 0.62,
    reviewSensitivity: 0.58,
    shippingSensitivity: 0.52,
    raceToBottomRisk: 0.6,
    defaultMinMarginPercent: 30,
  },
  society6: {
    marketplace: "society6",
    displayName: "Society6",
    commissionRate: 0.1,
    paymentFeeRate: 0,
    paymentFixedFee: 0,
    priceEnding: 0.0,
    rankingSensitivity: 0.55,
    reviewSensitivity: 0.5,
    shippingSensitivity: 0.48,
    raceToBottomRisk: 0.52,
    defaultMinMarginPercent: 30,
  },
  fine_art_america: {
    marketplace: "fine_art_america",
    displayName: "Fine Art America",
    commissionRate: 0.15,
    paymentFeeRate: 0,
    paymentFixedFee: 0,
    priceEnding: 0.0,
    rankingSensitivity: 0.45,
    reviewSensitivity: 0.62,
    shippingSensitivity: 0.4,
    raceToBottomRisk: 0.32,
    defaultMinMarginPercent: 45,
  },
  gelato: {
    marketplace: "gelato",
    displayName: "Gelato",
    commissionRate: 0,
    paymentFeeRate: 0.029,
    paymentFixedFee: 0.3,
    priceEnding: 0.99,
    rankingSensitivity: 0.32,
    reviewSensitivity: 0.44,
    shippingSensitivity: 0.78,
    raceToBottomRisk: 0.4,
    defaultMinMarginPercent: 36,
  },
  fourthwall: {
    marketplace: "fourthwall",
    displayName: "Fourthwall",
    commissionRate: 0.05,
    paymentFeeRate: 0.029,
    paymentFixedFee: 0.3,
    priceEnding: 0.99,
    rankingSensitivity: 0.35,
    reviewSensitivity: 0.68,
    shippingSensitivity: 0.72,
    raceToBottomRisk: 0.35,
    defaultMinMarginPercent: 38,
  },
};

export function getMarketplaceProfile(marketplace: PodMarketplace) {
  return MARKETPLACE_PRICING_PROFILES[marketplace];
}
