import { fal } from "@fal-ai/client";
import type { GenerateImageRequest, GeneratedImage, AspectRatio } from "../image-types";

// Note: Ensure FAL_KEY is set in your environment variables.
// The @fal-ai/client expects FAL_KEY or it can be configured via credentials.

function mapAspectRatio(ratio: AspectRatio): string {
  // Flux Schnell supports specific image size strings or custom dimensions
  switch (ratio) {
    case "1:1": return "square";
    case "4:3": return "landscape_4_3";
    case "3:4": return "portrait_4_3";
    case "16:9": return "landscape_16_9";
    case "9:16": return "portrait_16_9";
    default: return "square";
  }
}

export async function generateFalImages(
  req: GenerateImageRequest,
  count = 4
): Promise<GeneratedImage[]> {
  const FAL_KEY = process.env.FAL_KEY;
  if (!FAL_KEY) {
    throw new Error("FAL_KEY is not configured in environment variables.");
  }

  // Flux Schnell is extremely high quality and fast
  const modelId = "fal-ai/flux/schnell";

  const enhancedPrompt = `
    Design for Print-on-Demand (POD). 
    Style: ${req.style !== 'none' ? req.style : 'Commercial graphic design'}.
    Subject: ${req.prompt}.
    Platform: ${req.platform}.
    Technical: Professional POD artwork, clean composition, vibrant, market-ready, 
    high detail, isolated elements if applicable.
  `.trim();

  // Fal allows multiple images in some models, but for Flux Schnell we usually run parallel requests
  // for the best control or use the 'num_images' parameter if supported by the specific model version.
  
  const tasks = Array.from({ length: count }).map(async (_, i) => {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result: any = await fal.subscribe(modelId, {
        input: {
          prompt: enhancedPrompt,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          image_size: mapAspectRatio(req.aspectRatio) as any,
          num_inference_steps: 4, // Schnell is optimized for 4 steps
          enable_safety_checker: true,
          sync_mode: true,
        },
        logs: false,
      });

      if (!result.images || result.images.length === 0) {
        throw new Error("No image generated by Fal AI");
      }

      const imageData = result.images[0];

      return {
        id: `fal-${Math.random().toString(36).slice(2, 10)}`,
        url: imageData.url,
        prompt: req.prompt,
        style: req.style,
        aspectRatio: req.aspectRatio,
        platform: req.platform,
        createdAt: new Date().toISOString(),
        isFavorite: false,
      };
    } catch (err) {
      console.error(`Fal AI Error (Task ${i}):`, err);
      throw err;
    }
  });

  return Promise.all(tasks);
}
